
import React from "react";
import { Inter, Open_Sans } from "next/font/google";
import { Suspense } from "react";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import { ModalProvider, Modal } from "@context/Modal";
import Error from "./error";
import StoreProvider from "./StoreProvider";
import Loading from "./loading";
import App from "./App";
import '@app/globals.css';

// allow use of fontawesome icons
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const inter = Inter({ subsets: [ "latin" ] });

export const metadata = {
  title: "Productivity App",
  description: "Generated by create next app",
};

// open sans font
export const open_sans_init = Open_Sans({
  subsets: [ "latin" ],
  variable: "font-open-sans",
});

export default async function RootLayout({ children }) {
  return (
    <React.StrictMode >
      <html lang="en" className={inter.className}>
        <body className={`tracking-wide min-h-screen w-vw overflow-x-hidden min-w-[600px] overflow-y-scroll ${open_sans_init.variable}`}>
          <ModalProvider>
            <StoreProvider>
              <ErrorBoundary fallback={<Error />} />
              <Suspense fallback={<Loading />} />
              <App>
                {children}
              </App>
              <Modal />
            </StoreProvider>
          </ModalProvider>
        </body>
      </html>
    </React.StrictMode >
  );
}
