
import React from "react";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import Navigation from "@components/Navigation";
import { ModalProvider, Modal } from "@context/Modal";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";

// allow use of fontawesome icons
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import Error from "./error";
import "./globals.css";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata = {
  title: "Productivity App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {



  return (
    <React.StrictMode >
      <html lang="en">
        <body className="h-auto w-auto flex flex-col box-border">
          <ModalProvider>
            <StoreProvider>
              <Navigation />
              <ErrorBoundary fallback={<Error />} />
              {children}
              <Modal />
            </StoreProvider>
          </ModalProvider>
        </body>
      </html>
    </React.StrictMode>
  );
}
